# Generated by Django 4.2.11 on 2024-04-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grantee', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=25)),
                ('file', models.FileField(upload_to='annual_totals')),
            ],
            options={
                'verbose_name_plural': 'Annual Totals',
            },
        ),
        migrations.CreateModel(
            name='CummulativeTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grantee', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='cummulative_totals')),
            ],
            options={
                'verbose_name_plural': 'Cummulative Totals',
            },
        ),
        migrations.CreateModel(
            name='SUMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grantee', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('quota', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to='files')),
            ],
            options={
                'verbose_name_plural': 'SUMS',
            },
        ),
    ]
