# Generated by Django 4.2.11 on 2024-04-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grantee', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=25)),
                ('file', models.FileField(upload_to='annual_totals')),
            ],
        ),
        migrations.AlterModelOptions(
            name='sums',
            options={'verbose_name_plural': 'SUMS'},
        ),
    ]
