# Generated by Django 4.2.11 on 2024-04-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_annualtotals_alter_sums_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CumulativeTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grantee', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='cummulative_totals')),
            ],
        ),
        migrations.AlterModelOptions(
            name='annualtotals',
            options={'verbose_name_plural': 'Annual Totals'},
        ),
    ]
